DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE DESTINATION CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE EXPORT CASCADE CONSTRAINTS;
DROP TABLE QUALIFICATION CASCADE CONSTRAINTS;
DROP TABLE QUALIFICATION_DETAIL CASCADE CONSTRAINTS;
DROP TABLE SALARY_HISTORY CASCADE CONSTRAINTS;
DROP TABLE SHIFT CASCADE CONSTRAINTS;
DROP TABLE MINE CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;

SELECT 'drop view '||view_name||';' AS statements
from all_views
where owner = 'HR';

DROP INDEX MINES_WORKERS;
DROP INDEX DEPARTMENT_WORKERS;
DROP INDEX WORKERS_PER_SHIFT;
DROP INDEX idx_Exports;
DROP INDEX idx_Dates;
DROP INDEX idx_Sal_Date;