--SHIFT:
CREATE INDEX idx_Shifts ON SHIFT (Shift_Start,Shift_end);
--EMPLOYEE:
CREATE INDEX MINES_WORKERS ON EMPLOYEE(Mine_ID, Emp_ID); 
CREATE INDEX DEPARTMENT_WORKERS ON EMPLOYEE (Dep_ID, Emp_ID);
CREATE INDEX WORKERS_PER_SHIFT ON EMPLOYEE (Shift_ID, Emp_ID);
--EXPORT:
CREATE INDEX idx_Exports ON EXPORT (Mine_ID, Dest_ID);
CREATE INDEX idx_Dates ON EXPORT (Ship_date, Arrival_Date);