--DEPARTMENT:
CREATE UNIQUE INDEX DEPARTMENT_INDEX1 ON DEPARTMENT (DEP_CONTACTNUMBER ASC)
--SHIFT:
CREATE INDEX SHIFTS_INDEX ON SHIFT (SHIFT_ID);
--EMPLOYEE:
CREATE INDEX MINES_WORKERS ON EMPLOYEE(Mine_ID, Emp_ID); 
CREATE INDEX DEPARTMENT_WORKERS ON EMPLOYEE (Dep_ID, Emp_ID);
CREATE INDEX WORKERS_PER_SHIFT ON EMPLOYEE (Shift_ID, Emp_ID);
--EXPORT:
CREATE INDEX idx_Exports ON EXPORT (Mine_ID, Dest_ID);
CREATE INDEX idx_Dates ON EXPORT (Ship_date, Arrival_Date);
--SALARY HISTORY:
CREATE UNIQUE INDEX idx_Sal_Date ON SALARY_HISTORY(Sal_Date);